Repository ssg-240304-java2/JD-HeadBang, pull requests merged in 2024-04, with the labels that each got.

#13 #12 wip: 검색 기능 2/3
  build.gradle
  src/main/java/module-info.java
  src/main/java/music/domain/Search.java
  src/main/java/music/domain/dto/AlbumDTO.java
  src/main/java/music/domain/dto/TrackDTO.java
Labels: enhancement

#25 feat. 메소드명 수정
  src/main/java/module-info.java
  src/main/java/music/domain/Search.java
  src/main/java/music/ui/console/Command.java
  src/main/java/music/ui/console/CommandHandler.java
  src/main/java/music/ui/console/PurchaseCommand.java
  src/main/java/music/ui/console/SearchCommand.java
  src/main/java/music/ui/console/SongCommand.java
  src/main/java/music/ui/console/SortCommand.java
  src/main/java/music/ui/console/purchase_Command.java
  src/main/java/view/PrintList.java
Labels: develop

#27 - dev 정렬 메뉴 이동및 top50곡 출력 메소드 생성 및 엘범이 재대로 나오지 않는 버그 해결
  src/main/java/music/ui/console/CartController.java
  src/main/java/music/ui/console/CommandHandler.java
  src/main/java/music/ui/console/PrintList.java
  src/main/java/music/ui/console/SearchCommand.java
  src/main/java/music/ui/console/SongCommand.java
Labels: bug, develop

#30 TrackDto 타입 사용하도록 수정
  src/main/java/music/application/CartService.java
  src/main/java/music/domain/CartRepository.java
  src/main/java/music/domain/Search.java
  src/main/java/music/domain/dto/AlbumDTO.java
  src/main/java/music/infrastructure/CartInMemoryRepository.java
  src/main/java/music/service/Database.java
  src/main/java/music/ui/console/CartController.java
  src/main/java/music/ui/console/CommandHandler.java
  src/main/java/music/ui/console/PrintList.java
Labels: develop
